"""create room_instances table

Revision ID: 3f7fbf51d42b
Revises: 1e0168470040
Create Date: 2026-09-12 11:32:02.380773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7fbf51d42b'
down_revision: Union[str, Sequence[str], None] = '1e0168470040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_type_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_instances_room_type_id'), 'room_instances', ['room_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_instances_room_type_id'), table_name='room_instances')
    op.drop_table('room_instances')
    # ### end Alembic commands ###
